### ISSUE TITLE
Routes available in App

### ISSUE THREAD

**Issue by Israel-Laguan** [Azordev/dasher-user#11]
If we check the Design (#2) we can note these routes:

## `home` or root (`/`)

- [x] #42

![image](https://user-images.githubusercontent.com/36519478/134940301-4d4e5a01-9b38-49e9-ae3c-ba62b0b14dbb.png)

## `check`

- [x] #48

![image](https://user-images.githubusercontent.com/36519478/134832825-8f5f27ce-351e-45b7-956b-651fe3aa035b.png)

## `delivery/:id`

- [x] #39 

![image](https://user-images.githubusercontent.com/36519478/135971354-dfcbba85-4e4d-471f-840b-252848c9f4a3.png)

# `chat/:id`

- [x] #40

![image](https://user-images.githubusercontent.com/36519478/134835165-124f26ba-56bd-40ed-89b5-34b88917ff31.png)

Related issues
 
- #31
- #34 

## `confirm/:id`

- [x] #43

![image](https://user-images.githubusercontent.com/36519478/134838120-865d5e82-2c68-4caa-8c2e-52bfe0c2e24d.png)

## error 404 and error 5XX

- [x] #49

![image](https://user-images.githubusercontent.com/36519478/134840367-0f82f170-c5f0-4a98-ae3f-e553ab1e00c9.png)

- [ ] app error 5XX

TBD

Notice:
- Should include id and timestamp of error
- Should include developer/technical staff contact information
- Should have a link to Home or other TBD

## Checklist

- [x] Define the route links to access the views
- [x] A router package is added to manage routes
- [x] This package doesn't break the app
- [x] A user can change between routes using URL and using links
- [x] There is a fallback for a not found route
- [ ] There is a way to show errors 5xx

**Comment by heliomar-pena** [comment]
Define routes is different that create the views, or I'm wrong?. 

I think the "related issues" should be in each issue and not here, since if this issue is not about complete the views to 100%, would be more useful to have that information in each issue that has the objective to complete the view.

Confirm what is the objective of this issue:

1. Define and create the route links to access to the views (This issue will be closed when are defined the URL and view files are created)
2. Create the views (This issue will be closed when all views look and work how is expected)
3. Discuss with the team about what views are needed create to the project

**Comment by AlejandroSalcido** [comment]
All the user interface seems covered with those routes, i like the name of the sections, but i would change map for menu or something that includes more of the whole functionality of that section.

**Comment by Israel-Laguan** [comment]
What about `delivery` for the view related to show the map and chat, confirm options? @AlejandroSalcido

**Comment by AlejandroSalcido** [comment]
> What about `delivery` for the view related to show the map and chat, confirm options? @AlejandroSalcido

delivery would be better, it is a more accurate name!

**Comment by Israel-Laguan** [comment]
When we manage internal errors we can close this
